:filter:
  - :function:
      :type: gte
      :target:
        :value: 4500
      :function:
        :type: sum
        :list: sales
        :property: amount
  - :function:
      :type: member
      :properties:
        - scores.month
      :facts:
        - jan
:transform:
  - :assign_each:
      :list: sales
      :property: rate
      :value: 0.2
